name: Continuous Deployment

on:
  release:
    types: [published]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # Source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Runtime
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm test

      # Build
      - name: Build
        run: npm run build

      # Publish to Netlify
      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
